### ISSUE TITLE
Functionality Bug (Group-3) :-  Inconsistent Account Creation and Login Behavior

### ISSUE THREAD

**Issue by ishikajain212** [IITGN-CS431/project-cns#171] opened 2024-10-28 19:09 UTC
It is possible to log in to an account that shows an error when attempting to create it, as demonstrated in the attached file. Attempt to create an account with a specific card file (e.g., card10000), which returns an error indicating the card file already exists.
Despite the error, log in with the same credentials successfully.
another error in login is that the system allows the creation of multiple accounts using the same card file, which should not be permitted. As create another account using the same card file, which is incorrectly allowed.

I have mention all the issues in attached file as well :-

![WhatsApp Image 2024-10-29 at 00 12 03_af6228b1](https://github.com/user-attachments/assets/e1a2a085-f8f5-4270-8e87-defcea194f76)

**Comment by bichhawat** [comment] 2024-10-29 06:10
I am not sure what the issue is. If I understand correctly, they are appending the account details with card details to get a card. If you can use the existing PIN to login, that would be an issue.

**Comment by Quantizate** [comment] 2024-10-29 07:57
So the functionality is that we have an option of users having the same card name. The user just needs to mention the initial card file name they make and we internally handle the multiple card files.

**Comment by bichhawat** [comment] 2024-10-29 10:55
It seemed so; I will close this but @ishikajain212, if there are issues due to that, please report them as a separate issue.

**Closed by bichhawat** 2024-10-29 10:55 UTC
