### ISSUE TITLE
Functionality bug (Group-2)

### ISSUE THREAD

**Issue by pranjal15195gaur** [IITGN-CS431/project-cns#305] opened 2024-11-18 17:06 UTC
same command running directly but not on the client 
![Screenshot 2024-11-18 223419](https://github.com/user-attachments/assets/272b5d14-c850-4d94-927f-b43d6bc8713c)

**Comment by bichhawat** [comment] 2024-11-19 10:17
I am not sure what the issue is here. Can you please elaborate it?

**Comment by pranjal15195gaur** [comment] 2024-11-19 10:36
Here, there is no constraint on the logfile name length normally, but when it is run on the client, there is a constraint on the length of the logfile name, which gives an error when run on the client.
So, Either both should have the same constraint, or both should accept any length.

**Comment by naveeeeeeeeeen** [comment] 2024-11-20 13:13
Hi @pranjal15195gaur,

This is not a bug per se.

Clients are not allowed to run ./setup, ./logappend, or ./logread directly, as these files are only present on the server side. Clients only have access to client.py, which they use to connect to the server and send commands.

Regarding the different behavior , the server will reject excessively long file names, close the connection for that client, and require a reconnection to send valid commands.

Refer to PR #323 and PR #324.

![Screenshot from 2024-11-20 14-34-23](https://github.com/user-attachments/assets/ea6c674b-5f3a-495c-8a1c-4ceab916f2c3)

The server will continue running smoothly, and there is no file tampering or password leak.

@bichhawat Sir, Please review.

P.S. Please use the latest code and ensure all PRs are merged before running it.

**Closed** 2024-11-21 06:43 UTC
Labels: bug, functionality
